### ISSUE TITLE
Circuit PSI with associated data benchmarking

### ISSUE THREAD

**Issue by jimouris** [Visa-Research/volepsi#34]
Hi and thanks for this great work!

I have a few questions, I'm adding numbers so it'll be easier to respond :) 

1) I want to run a circuit PSI example with associated data between two parties each of which has a set of 10^6 elements (`party_0.csv` and `party_1.csv`). Are the following commands correct?
```
./frontend -cpsi -v -nt 1 -t 1 -in party_0.csv -r 0
./frontend -cpsi -v -nt 1 -t 1 -in party_1.csv -r 1
```

My two sets contain one value per line and have an intersection of 50%. For instance `party_0.csv`:
```
vCoS1hU3O19TnaAM
ZQOOOZ9dG0bLRutA
Iyw6AAc1v32JhBHl
...
```

The reason I'm asking is that I saw in your [paper](https://eprint.iacr.org/2021/266.pdf) in Table 2 that for 2^20 (which is a little above 1M) it takes 4-5 seconds in LAN but when I run it, it runs in less than 2 seconds on my laptop:
```
reading set... 276ms
connecting as server at address localhost:1212 56ms
Validating set sizes... 0ms
running PSI... 1642ms
```

2) Also, is there a way to choose between the IKNP and the SilentOT versions?

3) On a different note, is there a way to provide the associated data or is this not supported yet? If it's supported, is there a way to provide multiple columns of associated data? Like, party A has dataset `X` and associated data `A_0, B_0, C_0` and party B has dataset `Y` with associated data `A_1, B_1, C_1`. Each of `A_0, B_0, C_0` has as many elements as the corresponding dataset of the party.

4) Finally, just to clarify, to get the runtime for one PSI the number of trials `-t` parameter should be 1, right?

Sorry for the multiple questions and thank you!
Dimitris

**Comment by ladnir** [comment]
It is supported but there is no command line tool to run it. 

For the sender, you need to pass the associated data in here as the `values` parameter. 
https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsCpsi.h#L88

The resulting shared are written to here. 
https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsCpsi.h#L77
https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsCpsi.h#L105

The receiver can also have associated values but the process works a bit differently. The receiver learns a 'mapping' that tell them which input value was mapped to _position_ `i`. That is, position `i` will hold the _input with index_ `mMapping[i]`. Note that `mMapping` will have 30% empty spots. They are denoted with `mMapping[i]=-1`. So for the receiver to give associated values, they can just add them after since they know the mapping.
https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsCpsi.h#L108 

Note that the sender also holds a mapping but this mapping is a bit ambiguous in that the sender knows that _input with index_ `i` was mapped to one of the _positions_ `mMapping[i][0],mMapping[i][1],mMapping[i][2]`. 
https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsCpsi.h#L82

**Comment by ladnir** [comment]
1) you can not use the file based PSI code with circuit PSI. This only works for normal PSI. 

2) For circuit psi, you can only use silent ot and the default version of silent ot is with the Expand Accumulate code. Not with the faster but experimental Silver code.

You could modify the code to use IKNP or the better SoftSpoken OT protocol. This comes at a higher communication cost but better computational overhead.

3) as explained above, you can provide multiple associated values. You should just pack them together into the parameter `oc::MatrixView<u8> values`. There should be `n` rows and however many columns you want. each row is one associated values, so party A will have `X` and `A_0, B_0, C_0` where element `X[i]` is associated with `A_0[i], B_0[i], C_0[i]`. You should then have `values[i]=(A_0[i], B_0[i], C_0[i])`.

4) for `-perf -cpsi`, all trails are added together and you get one value for the total running time https://github.com/Visa-Research/volepsi/blob/main/frontend/perf.cpp#L489

**Comment by jimouris** [comment]
I see, great! Thank you for your quick responses! Is there any example/instructions to invoke CPSI or do I need to call these two functions from my own C++ files?

**Comment by ladnir** [comment]
here's an example https://github.com/Visa-Research/volepsi/blob/main/tests/RsCpsi_Tests.cpp#L40

you have to write your own frontend code. Maybe something similar to this if you want it to run on the command line https://github.com/Visa-Research/volepsi/blob/main/volePSI/fileBased.cpp#L230

**Comment by jimouris** [comment]
Got it, thanks again! I'll follow the file-based PSI that has functionality separately for the sender and the receiver. When I get some time to clean it up I might send a PR :)
