### ISSUE TITLE
question   about efficiency between dynamic libraries and  the example in fronted

### ISSUE THREAD

**Issue by jhjiang10** [Visa-Research/volepsi#35]
Hi and thanks for this great work!
I have a few questions。
When I use dynamic libraries, I find my speed is nearly twice as slow as the example in fronted. Is that why I use -pic? There are some good solutions。
A million data can be done in about 2s, but it takes about 6s to use the dynamic library

**Comment by ladnir** [comment]
There should be no difference due to static VS shared. I'm not sure what the issue is. Maybe you are not compiling in release mode.

The idea of Pic is that you can compile a static library and then link this into your own shared library. Your shared library will contain the vole psi static library.

**Comment by jhjiang10** [comment]
Thanks！I will try this to do so.

**Comment by jhjiang10** [comment]
I have tried to do so and the speed is the same. Thank you for your reply。
