### ISSUE TITLE
About the network socket

### ISSUE THREAD

**Issue by Fix3dP0int** [Visa-Research/volepsi#58]
Hello! I want to use this socket lib to communicate among more than three machines or programs. Could you give me a simple example like just send a string and receive it among them, please?

**Comment by ladnir** [comment]
well here is now you can use boost asio to create a tcp connection between two parties. 

https://github.com/Visa-Research/volepsi/blob/main/frontend/networkSocketExample.h#L89

The party that is the server should use their local IP address. The client party should use the server's IP address.

You can connect 3 ways just be repeating this. For each pair of parties you just do the same thing. If all parties are on the same machine, you can use `localhost` and give each server a different port. For example

```c++
auto client0 =  coproto::asioConnect("localhost:1212", true);
auto server0 =  coproto::asioConnect("localhost:1212", false);
auto client1 =  coproto::asioConnect("localhost:1213". true);
auto server1 =  coproto::asioConnect("localhost:1213", false);
auto client2 =  coproto::asioConnect("localhost:1214", true);
auto server2 =  coproto::asioConnect("localhost:1214", false);
```

So the code above will just deadlock because these calls are blocking and the client will wait for the server, but the server hasn't stated. So you could do this if you ran each statement in different threads. Or you can use `macoro::when_all_ready` on the underlying tasks https://github.com/Visa-Research/coproto/blob/main/coproto/Socket/AsioSocket.h#L1451
```c++
auto addr0 = "localhost:1212";
auto addr1 = "localhost:1213";
auto addr2 = "localhost:1214";
auto r = macoro::sync_wait(macoro::when_all_ready(
	macoro::make_task(AsioConnect(addr0, ioc)),     // client 0
	macoro::make_task(AsioAcceptor(addr0, ioc, 1)), // server 0
	macoro::make_task(AsioConnect(addr1, ioc)),     // client 1
	macoro::make_task(AsioAcceptor(addr1, ioc, 1)), // server 1
	macoro::make_task(AsioConnect(addr2, ioc)),     // client 2
	macoro::make_task(AsioAcceptor(addr2, ioc, 1))  // server 2
));

auto client0 =  std::get<0>(r).result();
auto server0 =  std::get<1>(r).result();
auto client1 = std::get<2>(r).result();
auto server1 =  std::get<3>(r).result();
auto client2 =  std::get<4>(r).result();
auto server2 =  std::get<5>(r).result();
```

I haven't tested this so might have error. but generally right.

**Comment by Fix3dP0int** [comment]
OK. It works successfully! Thank you very much!
